version: '3.8'

services:
  # inicio configuracion del servicio mysql
  mysqldb:
    image: mysql # Imagen que sera utilizada
    # ruta de las variables del entorno que vamos a utilizar
    env_file: ./.env 
    # Variables de entorno definidas en el archivo .env 
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    # Puerto de la base de datos que estamos utilizando
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

  # Configuración del servicio de la aplicacion de node.js
  app:
    # Ruta del Dockerfile para la creacion del servicio de Node.js
    build: .
    # Servicio del que depende
    depends_on:
      - mysqldb
    # Comunicación entre los servicios
    links:
      - mysqldb
    # Puertos de la aplicación
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
